//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_PESPIRE_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public int CategoriaId { get; set; }
        public string NombreCategoria { get; set; }
        public byte[] Imagenlustracion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaModificado { get; set; }
        public int FKUsuarioId { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
