//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_PESPIRE_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolModuloAcciones
    {
        public int FKRolId { get; set; }
        public int FKAccionId { get; set; }
        public int FKModuloId { get; set; }
    
        public virtual Acciones Acciones { get; set; }
        public virtual Modulos Modulos { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
